spring.datasource.url=jdbc:postgresql://localhost:5432/indusmate
spring.datasource.username=mohamedshafi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

bolt.api-key=4fb18bf7-5a76-483d-a36f-a75577be5977
bolt.device-id=BOLT6470541
bolt.pin=A0