spring.application.name=indusmate-backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.application.name=indusmate-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/indusmate
spring.datasource.username=mohamedshafi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true