spring.datasource.url=jdbc:postgresql://localhost:5432/indusmate
spring.datasource.username=mohamedshafi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

bolt.api-key=16dc6424-0c96-4ef1-9eeb-0eda2348a3f0
bolt.device-id=BOLT6470541
bolt.pin=A0